# Generated by Django 4.0.1 on 2022-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0002_post_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
