# Generated by Django 4.0.1 on 2022-02-09 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0005_rename_body_reply_bodyr_rename_name_reply_namer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
