# Generated by Django 4.0.1 on 2022-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0006_alter_post_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrL', models.CharField(max_length=50)),
                ('arrC', models.CharField(max_length=50)),
                ('arrR', models.CharField(max_length=50)),
                ('topL', models.PositiveIntegerField()),
                ('topC', models.PositiveIntegerField()),
                ('topR', models.PositiveIntegerField()),
            ],
        ),
    ]
