# Generated by Django 4.0.1 on 2022-02-10 21:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0008_alter_layoutrow_arrc_alter_layoutrow_arrl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short', ckeditor.fields.RichTextField()),
                ('full', ckeditor.fields.RichTextField()),
                ('add', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
