# Generated by Django 4.0.1 on 2022-02-11 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0009_topic_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='test',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
