# Generated by Django 4.0.1 on 2022-02-11 20:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0010_topic_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='fullest',
            field=ckeditor.fields.RichTextField(default='description'),
            preserve_default=False,
        ),
    ]
