# Generated by Django 4.0.1 on 2022-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishmap', '0011_topic_fullest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutRow1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrL', models.CharField(blank=True, max_length=50, null=True)),
                ('arrC', models.CharField(blank=True, max_length=50, null=True)),
                ('arrR', models.CharField(blank=True, max_length=50, null=True)),
                ('topL', models.PositiveIntegerField(blank=True, null=True)),
                ('topC', models.PositiveIntegerField(blank=True, null=True)),
                ('topR', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
